"""Add agent fields to InternetAccessLog

Revision ID: 2c845d763b8f
Revises: 
Create Date: 2026-02-01 13:40:46.001369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c845d763b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internet_access_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('process_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_context', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_ial_ip_time'))
        batch_op.drop_index(batch_op.f('idx_ial_timestamp_desc'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internet_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ial_timestamp_desc'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_ial_ip_time'), ['ip_address', 'timestamp'], unique=False)
        batch_op.drop_column('user_context')
        batch_op.drop_column('process_name')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
